In [72]:
# imports
import pandas as pd
from ast import literal_eval

In [73]:
# read authors data and get overall overview
authors = pd.read_csv('../data/authors.csv')
authors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   author_id        374 non-null    int64
 1   FullName         374 non-null    object
 2   HIndex           374 non-null    int64
 3   research_sector  374 non-null    int64
dtypes: int64(3), object(1)
memory usage: 11.8+ KB

In [74]:
# analyze authors id duplicated
authors[authors.author_id.duplicated(keep=False)]

Empty DataFrame
Columns: [author_id, FullName, HIndex, research_sector]
Index: []

In [75]:
# analyze authors full name duplicated
authors[authors.FullName.duplicated(keep=False)]

         author_id                 FullName  HIndex  research_sector
6     352187825414                I. Mandić       2          1631149
34   1494649202701                G Testera       2         23376214
54   1082332353958              L. X. Chung       2         27313889
60    335007990736                I. Mandić      48          1631149
128   498216830546  Pauline Hall Barrientos       4         17040978
250  1022202726879                G Testera       6         23376214
294  1133871876862             J.-Y. Roussé      10         27313889
302    17180409555             J.-Y. Roussé       8         27313889
303   214748918399  Pauline Hall Barrientos       4         17040978
305   798864434338              L. X. Chung       2         27313889

In [76]:
# read publications data and get overall overview
publications = pd.read_csv('../data/publications.csv')
publications.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PublicationId     244 non-null    int64
 1   authors           244 non-null    object
 2   topics            244 non-null    object
 3   publication_year  244 non-null    int64
 4   Doi               244 non-null    object
dtypes: int64(2), object(3)
memory usage: 9.7+ KB

In [77]:
# publications data sample
publications.head(25)

,PublicationId,authors,topics,publication_year,Doi
0,465031,"['id:300648343950, name:Tadeusz Kaczorowski'\n...",[185592680 89423630],2019,10.3390/V11070657
1,8590182776,"['id:1151051732647, name:E. Paoloni' 'id:16406...",[192562407 120665830],2016,10.1088/1748-0221/11/12/C12018
2,8590359559,"['id:987842971362, name:Z. Galloway' 'id:33500...",[ 49040817 121332964],2019,10.1016/J.NIMA.2018.08.041
3,8590382155,"['id:962073216979, name:S. Zhamkochyan'\n 'id:...",[121332964 185544564],2019,10.1016/J.NIMA.2019.04.063
4,8590416941,"['id:111669774394, name:Eva Nordberg Karlsson'...",[185592680 55493867],2019,10.1107/S2059798319013330
5,17180318214,"['id:51540165879, name:L. Bosisio' 'id:1520419...",[121332964 185544564],2020,10.1016/J.NIMA.2019.05.025
6,34360166020,"['id:987842971362, name:Z. Galloway'\n 'id:627...",[ 49040817 121332964],2019,10.1016/J.NIMA.2018.08.123
7,34360228672,"['id:1477469340278, name:R G H Robertson'\n 'i...",[121332964 114614502],2020,10.1088/1742-6596/1342/1/012026
8,51539698674,"['id:197569082586, name:Michele Montuschi'\n '...",[121332964 185544564],2016,10.1088/1742-6596/675/1/012025
9,51539963557,"['id:635655697657, name:Astrid James'\n 'id:24...",[161191863 71924100],2017,10.1371/JOURNAL.PMED.1002315
10,60129896704,"['id:730144966089, name:R. Henning' 'id:970663...",[121332964 185544564 109214941],2017,10.1103/PHYSREVLETT.118.161801
11,85899868620,"['id:1486059188819, name:Valentino Di Marcello...",[121332964 185544564 109214941],2020,10.1140/EPJC/S10052-020-08534-2
12,103079710644,"['id:1486059188819, name:Valentino Di Marcello...",[121332964 185544564 109214941],2020,10.1103/PHYSREVD.101.062001
13,120259104991,"['id:1477469340278, name:R G H Robertson'\n 'i...",[ 49040817 121332964 185544564],2015,10.1016/J.PHPRO.2014.12.104
14,146029106046,"['id:1297080616110, name:T. Tsuboyama'\n 'id:1...",[ 49040817 121332964],2016,10.1016/J.NIMA.2016.04.110
15,146029380441,"['id:635655697657, name:Astrid James'\n 'id:24...",[509550671 71924100],2020,10.1056/NEJME2000647
16,154619078011,"['id:1563368658745, name:T Strub' 'id:78168454...",[121332964 185544564 109214941],2015,10.1103/PHYSREVC.92.024617
17,154619247372,"['id:1159641696630, name:C. Garcia Argos'\n 'i...",[121332964 120665830],2019,10.1016/J.NIMA.2018.08.031
18,163209005806,"['id:1151051732647, name:E. Paoloni' 'id:16406...",[ 9390403 119599485 41008148],2015,10.1088/1748-0221/10/02/C02024
19,171799095002,"['id:472446930578, name:Kazuhiko Hara'\n 'id:1...",[121332964 120665830],2018,10.1088/1748-0221/13/01/C01037
20,171799182602,"['id:635655697657, name:Astrid James'\n 'id:24...",[509550671 71924100],2020,10.1001/JAMA.2019.22274
21,188978936511,"['id:730144966089, name:R. Henning' 'id:970663...",[121332964 185544564 109214941],2017,10.1088/1742-6596/888/1/012035
22,206158668935,"['id:85899929381, name:J. Winter'\n 'id:197569...",[121332964 185544564],2016,10.1051/EPJCONF/201612602008
23,206158798903,"['id:17180409555, name:J.-Y. Roussé' 'id:42949...",[121332964 184779094],2017,10.1103/PHYSREVC.96.011301
24,223338427049,"['id:987842971362, name:Z. Galloway' 'id:12627...",[ 49040817 192562407],2016,10.1016/J.SSE.2015.11.029

In [82]:
foo = publications.topics[0]
foo

'[185592680  89423630]'

In [54]:
# get a single topic and a single author per publication row
publications.authors = publications.authors.apply(literal_eval)
publications.topics = publications.topics.split(' ')
foo_pub = publications.explode('authors')

foo_pub.head(25)

ValueError: malformed node or string: ['id:300648343950, name:Tadeusz Kaczorowskiid:566936217113, name:Anna-Karina Kaczorowskaid:214748948560, name:Sebastian Dorawa']

In [ ]:
# read topics data and get overall overview
topics = pd.read_csv('../data/topics.csv')
topics.info()

In [ ]:
# topics data sample
topics.head(25)

In [ ]:
# retrieve null name topic
topics.query('name.isnull()')

In [ ]:
# read incoming publications data and get overall overview
in_publications = pd.read_csv('../data/incomming_publications.csv')
in_publications.info()

In [ ]:
# incomming publications data sample
in_publications.head(25)